### ISSUE TITLE
Support NVMe

### ISSUE THREAD

**Issue by feifeibear** [Tencent/PatrickStar#229]
Similar to [DeepSpeed](https://www.deepspeed.ai/tutorials/zero/#offloading-to-cpu-and-nvme-with-zero-infinity).

**Comment by zhuzilin** [comment]
related issue #242 

在这里记录一下设计方案。

我们会按照 https://github.com/Tencent/PatrickStar/issues/242#issuecomment-976389824 中提到的，将优化器状态（OS）分为 3 部分，OS_cpu、OS_move 和 OS_nvme，分别表示一直在 CPU 上的 OS chunk、会在 adam 开始时 load 到 CPU，但是在 forward 过程中 offload 到 CPU 的 OS chunk 和一直在 nvme 上的 OS chunk。在 warmup 步的前后向计算完成后，模型首次进入 adam，可以通过已经收集到的 warmup 信息来计算出 3 部分 chunk 的数量。具体计算方法是：

1. OS_move chunk 数量对应 activation 的最大值。
2. OS_cpu 为除去 OS_move 后，在 adam 开始阶段最多能分配的 cpu chunk 数，注意要考虑哪些地方需要额外分配 chunk。
3. 其余 OS chunk 为 OS nvme 使用

在具体实现上，要考虑以下几个问题：

1. OS 的上述切分和放在 GPU 上的 OS chunk 的关系：

目前 gpu OS chunk 的使用方法是这样的：

```python
fp16_grad_tensor = read_chunk_buff.access_from_cache(fp16_param)
compute_device = fp16_grad_tensor.device

client.access_data(exp_avg_param, compute_device)
client.access_data(exp_avg_sq_param, compute_device)
```

这里 `access_from_cache` 会根据每一步的 `margin_chunk_num_for_gpu_adam` 来判别是否要把 grad tensor 拿到 GPU 上去。如果 grad tensor 放到 GPU 上去了，那么 OS chunk 就会被拿到 GPU 上去。所以只需要在 access_data 之前把 OS chunk 拿到内存上，就可以适应这种移动到 GPU 上的操作。

另外就是，我们暂时假设 margin chunk 是包含在 OS_cpu 里面的（这点有待实验考证），而现在的实现是会把前面 n 个 chunk 移动到 GPU 上，所以我们在标记 chunk 的时候需要把最前面的部分标注为 OS_cpu，并且可以暂时禁止让非 OS_cpu 的 chunk 被移动到 GPU。

2. 如何 offload OS chunk

为了更好地管理 OS chunk 的状态，其实可以通过添加 `access_optimizer_data` 和 `release_optimizer_data` 来解决。
