### ISSUE TITLE
Proposal: overlap NVMe read and write with computing.

### ISSUE THREAD

**Issue by feifeibear** [Tencent/PatrickStar#242]
定义：P param fp16 (grad fp16), OS (optimizer state)
假设1：GPU无法存放P，CPU+GPU可以存放P，CPU+GPU无法存放OS+P
假设2：access_chunk中的，CPU-GPU-NVME之间的通信无法和计算重叠。

ADMA : 
access_chunk的方向
GPU (P) -(P)-> CPU (P, OS) <-(OS)- NVMe (OS)
offload_chunk的方向
GPU (P) <-(P)- CPU (P, OS) -(OS)> NVMe (OS)

推论1：ADAM计算完CPU是满的。
推论2：FWD前GPU上的P是满的。

FWD :
access_chunk的方向
GPU (P) <-(P)- CPU (P, OS) <-(None)- NVMe (OS)
offload_chunk的方向
GPU (P) -(P)-> CPU (P, OS) **-(OS)->** NVMe (OS)
GPU上P总量减少->CPU上P总量增多。

BWD：
access_chunk的方向
GPU (P) <-(P)- CPU (P, OS) <-(None)- NVMe (OS)
offload_chunk的方向
GPU (P) -(P)-> CPU (P, OS) -(None)-> NVMe (OS)
GPU上P总量增多->CPU上P总量减少。

推论2：FWD+BWD时候需要OS以chunk为粒度向NVMe移动（如上加粗），这种移动穿插在FWD计算之间。
推论3：OS从来不会出现在GPU上。
推论4：有一部分OS一直在CPU上，我们称之为OS_cpu。
推论5：OS去除OS_cpu为OS_nvme.

优化：
在AMAM计算之后，FWD开始时异步offload OS_nvme到NVMe。这部分offload操作和FWD计算重叠。
这样可以减少FWD阶段细粒度的NVMe移动开销。
在FWD结束后，BWD开始前，我们把OS_nvme异步从NVMe移动到CPU上，这部分操作可以和BWD计算重叠。
这样可以减少ADMA阶段NVMe移动开销。

**Comment by zhuzilin** [comment]
嗯嗯，这样是可以减少一些移动开销。下面对 OS 划分策略稍微进行了一下计算：

这里有一个地方需要区分，就是 OS 实际上是分为 3 部分的：
- OS_cpu：一直都放在 cpu 上的 OS。满足：
  - M(OS_cpu) + M(P) + max(M(A, t)) <= M(GPU) + M(CPU)
  
  即：
  - M(OS_cpu)  <= M(GPU) + M(CPU) + M(P) - max(M(A, t))
  
  为了尽可能利用 CPU，同时减少 CPU 和 NVMe 之间的移动，我们会让 OS_cpu 尽可能大，我们不妨让上式取等号：

  - M(OS_cpu)  = M(GPU) + M(CPU) - M(P) - max(M(A, t))                                            **[1]**

- OS_move：可以移动的 OS；这部分 OS 会在开始 adam 计算的时候放在 CPU 上，而在正反向计算过程中，需要逐渐 offload 到 CPU 上去。满足：
  - M(OS_cpu) + M(OS_move) + M(P) + max(M(A, t)) > M(GPU) + M(CPU)
  - M(OS_cpu) + M(OS_move) + M(P) + M(A, t_adam) <= M(GPU) + M(CPU)  **[2]**
  
  将 **[1]** 带入 **[2]** 中，并且考虑到 M(A, t_adam) = 0，有：

  - M(OS_move) <= max(M(A, t))

  您这里提到的优化方法，相当于是把这部分的 load/offload 放到 FWD 和 BWD 的计算过程中进行。对于这个优化，我们不妨让
我们不妨让上式取等，也就是 M(OS_move) 相当于是 activation 的最大值 max(M(A, t))，即：

  - M(OS_move) = max(M(A, t))                    **[3]**

- OS_nvme：一直都放在 nvme 上的 OS；这部分 OS 只能临时放在 CPU 上，访问方法是取固定几个 CPU chunk 作为 buffer，以循环的方式去访问他们。

  注意到：

  M(OS) = M(OS_cpu) + M(OS_move) + M(OS_nvme) = 4 * M(P)

  把 **[1]**, **[3]** 带入 **[4]** 有：

  - M(OS_nvme)  = 5 * M(P) - M(GPU) - M(CPU)
 
所以理论上来说，对于一个 100B 的模型来说，M(P) = 200G，在 1T 的内存的场景下，应该不需要有 M(OS_nvme)。然后可以在 warmup 的时候统计 maxM(A, t)，从而规定好 OS_cpu 和 OS_move。

**Comment by zhuzilin** [comment]
暂时想到了这样的实现方案：

在完成 warmup 后，根据 activation 的最大值来计算出 OS_cpu 与 OS_move 对应的 chunk 数，并标记在对应的 optimizer state chunk 上。adam 开始时 OS_cpu 和 OS_move 都放在内存上，OS_nvme 通过共用 buffer 的形式循环访问。在 Adam 结束的时候，异步进行 OS_move 向 nvme 的写入，直到 forward 结束后，再逐渐移动回内存。

这个实现主要有 2 个问题：

1. 这意味着 nvme offload 这个操作目前是绑定在 optimizer 这个事儿上了。不过我认为这相较于 deepspeed 的把参数和 activation 放到 nvme 上实际是一种优化；
2. 这个异步写入可能需要用 C++ 实现，或者起一个新进程...
