### ISSUE TITLE
support using PatrickStar on MegatronDeepSpeed?

### ISSUE THREAD

**Issue by Jack47** [Tencent/PatrickStar#293]
PatrickStar is awesome, it helps reduce memory used by model state!

currently trends show using [MegatronDeepSpeed](https://github.com/microsoft/Megatron-DeepSpeed/blob/main/examples/pretrain_t5.sh) as framework to train transformer based NLP models, both pretrain and finetuing. so will you guys support PatrickStar on MegatronDeepSpeed?

**Comment by feifeibear** [comment]
You can easily follow the example to apply PatrickStar on T5.  We are considering releasing a T5 example if necessary. 
In our humble opinion, we double about the current trend you say, and Megatron+DeepSpeed is certainly not the final solution... As you can see ZeroDP only can train GPT3-175B on 32 GPU, which is impossible for MegatronDeepSpeed. 
DeepSpeed has involved too many config options in a black box style which has been not user-friendly to ML researchers already as we know.
We are working on some research to evaluate the factor of MP, PP, and DP in the redistributed context.

**Comment by Jack47** [comment]
PS's example is simple to follow.  As I known, lots of researcher are using MegatronDeepSpeed (DP+ZeRO), so I mean support PatrickStar on MDS as a plugin, no MP, PP.  I suppose supporting this will bring PS lots of new users.

**Comment by feifeibear** [comment]
> PS's example is simple to follow.
> 
> I mean support PatrickStar on MDS as a plugin, no MP, PP. As I known, lots of researchers are using MegatronDeepSpeed (DP+ZeRO), so supporting this may bring PS lots of new users!

Thanks for your advice. We are considering improving PatrickStar as a plugin.
